<?php
// This entire .module is ripped from islandora_collection_search.

// TODO: put this search in a block or sth that can be added to appropriate pages.
// Module currently exists in advanced search block...

// TODO: (later) figure out how to cache the results of the above search ^
//file_put_contents("cache_file", serialize($myArray));
//$myArray = unserialize(file_get_contents("cache_file"));
//check if cache_file exists

function islandora_namespaced_search_islandora_solr_query($islandora_solr_query) {
  // Query param 'ns' gets set on form submission so that we can use it here.
  if(!isset($_GET['ns'])){
    return;
  }
  $namespaces = $_GET['ns'];
  foreach($namespaces as $inst){
    if($namespace != '0'){
      $filter = format_string('!field:!value', array(
        '!field' => 'PID',
        '!value' => $inst,
      ));
  $islandora_solr_query->solrParams['fq'][] = $filter;
    }
  }
}

//how to update cache if new institution is added
if('cache_file'){
  //dpm('cache extant');
}
else{
  file_put_contents("cache_file", serialize(array_flip(get_all_collections_inst())));
}

function islandora_namespaced_search_form_islandora_solr_advanced_search_form_alter(&$form, &$form_state) {

  $form['namespaces'] = array(
    '#title' => 'Search within institutions',
    '#type' => 'checkboxes',
    // This is super-rough- I'm array-flipping here rather than re-type the array correctly (not backwards).

    '#options' => unserialize(file_get_contents('cache_file')),
    '#weight' => 5,
  );
  $form['controls']['#weight'] = 6;
  // Gives us a chance to add 'ns' to the URL for use in altering the query (above).
  $form['#submit'][] = 'islandora_namespaced_search_append_ns';
}


function islandora_namespaced_search_append_ns($form, &$form_state) {
  // set the 'ns' query param to be fetched later from $_GET
  //we have to unpack the array of checkbox items here somehow...
//  dpm($form_state['values']['namespaces']);
  if ($form_state['values']['namespaces'] != 'all') {
    $form_state['redirect'][1]['query']['ns'] = $form_state['values']['namespaces'];
  }
}


function get_all_collections_inst(){
  $connection = islandora_get_tuque_connection();
  if ($connection) {
    $query = <<<EOQ
  SELECT ?pid FROM <#ri>
  WHERE { 
    ?pid <fedora-rels-ext:isMemberOfCollection> <info:fedora/islandora:root>
  }
EOQ;
 $results = $connection->repository->ri->sparqlQuery($query);
  }
  $objects = array();
 foreach($results as $key => $value){
   $plode = explode('-', $results[$key]['pid']['value']);
   $objects[$plode[0]] =  $plode[0] . '*';
 }
 $objects['all'] = '*';
 return array_unique($objects);
}
